UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1004 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 2500000,f.account_balance=2500000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1004);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1005 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 1000000,f.account_balance=1000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1005);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1006 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 2500000,f.account_balance=2500000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1006);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1007 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 10000000,f.account_balance=10000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1007);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1009 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 10000000,f.account_balance=10000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1009);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1014 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 1000000,f.account_balance=1000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1014);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1510 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 1000000,f.account_balance=1000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1510);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1219 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 1000000,f.account_balance=1000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1219);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1220 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 1000000,f.account_balance=1000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1220);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1227 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 1000000,f.account_balance=1000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1227);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1229 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 1000000,f.account_balance=1000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1229);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1002 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 10000000,f.account_balance=10000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1002);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1012 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 10000000,f.account_balance=10000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1012);
UPDATE tbl_chargingorder c SET c.chOr_ChargingStatus = 2 where c.chOr_OrgNo =1003 AND c.chOr_ChargingStatus =3;
UPDATE fin_account f set f.account_warn = 10000000,f.account_balance=10000000 where f.account_id = (SELECT c.account_id from tbl_company c where c.cpy_number = 1003);
